apiVersion: v1
kind: Service
metadata:
  name: sealedissuer-svc
spec:
  type: ClusterIP
  selector:
    app: sealedissuer-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
