apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secret.yaml

patchesStrategicMerge:
- patch.yaml

namePrefix: prod-

commonLabels:
  environment: development
  country: sa
namespace: kustomize-darkstore