apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secret.yaml
- hpa.yaml

patchesStrategicMerge:
- patch.yaml

namePrefix: dev-

commonLabels:
  environment: production
  country: sa
namespace: kustomize-darkstore