architecture: "standalone"
auth:
  enabled: false
master:
  persistence:
    enabled: true
    size: "0.1Gi"
    #    resources:
    #      requests:
    #    memory: 64Mi
    #     cpu: 250m
    #  limits:
    #    memory: 128Mi
    #    cpu: 500m
replica:
  replicaCount: 1
  persistence:
    size: "0.1Gi"
  autoscaling:
    maxReplicas: 2    

