apiVersion: v1
kind: Service
metadata:
  name: erp-scv-{{ .Values.DeploymentID }} 
spec:
  selector:
    app : {{ .Values.DeploymentID }} 
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8069
      protocol: TCP
    - name: longpolling
      port: 81
      targetPort: 8072
      protocol: TCP
